# Creates docker container that runs HCP Pipeline algorithms
# Maintainer: Amy Hegarty (amy.hegarty@colorado.edu)
#

# Use Ubuntu 20.0.4 LTS
FROM amhe4269/hcp-icafix-base:1.06.15
#
# hcp-base:1.0.3 Install Set:
#   - FSL 6.0.4
#   - Connectome Workbench 1.5.0
#   - HCP Pipelines v4.3.0
#   - Freesurfer 6.0.1
#   - Washington-University/grandunwrap v1.2.0
#   - MSM_HOCR v3
#   - FSL-FIX 1.06.15
#   - Matlab Runtime Compiler


LABEL maintainer="Amy Hegarty <amy.hegarty@colorado.edu>"

# Installing main dependencies
ARG FLYWHEEL=/flywheel/v0
COPY pyproject.toml poetry.lock $FLYWHEEL/
RUN poetry install --no-root --no-dev

## Installing the current project (most likely to change, above layer can be cached)
## Note: poetry requires a README.md to install the current project
COPY run.py manifest.json README.md $FLYWHEEL/
COPY fw_gear_icafix $FLYWHEEL/fw_gear_icafix
COPY utils $FLYWHEEL/utils

# Configure entrypoint
RUN chmod a+x $FLYWHEEL/run.py && \
    echo "hcp-icafix" > /etc/hostname && \
    rm -rf $HOME/.npm

ENTRYPOINT ["poetry","run","python","/flywheel/v0/run.py"]

